<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headScript()->appendFile($this->assetUrl('js/browse.js'));
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');
$this->headLink()->prependStylesheet($this->assetUrl('vendor/chosen-js/chosen.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/chosen-js/chosen.jquery.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/chosen-options.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/are-item-browse.js'));
$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;

$layoutSetting = $this->themeSetting('browse_layout');
$gridState = ($layoutSetting == 'togglegrid') ? 'disabled' : '';
$listState = ($layoutSetting == 'togglelist') ? 'disabled': '';
$isGrid = (!isset($layoutSetting) || strpos($layoutSetting, 'grid') !== false) ? true : false;
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');

$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>

<div id="are-filters">
  <div id="filter-query" class="empty">
    <h4>Selected filters</h4>
    <ul class="selected-filters">
    </ul>
  </div>
  <?php 
    $resourceTemplates = $this->api()->search('resource_templates')->getContent();
    array_shift($resourceTemplates);
    $resourceTemplateIds = [];
    foreach($resourceTemplates as $resourceTemplate) {
      $resourceTemplateIds[$resourceTemplate->label()] = $resourceTemplate->id();
    }
    echo $this->partial('common/are-filter-select', [
        'heading' => 'Resource type',
        'filterResourceType' => 'resource_templates',
        'filterResources' => $resourceTemplates,
        'filterKey' => 'resource_template_id[]',
    ]); 

    $denominationFamiles = $this->api()->search('items', ['resource_template_id' => $resourceTemplateIds['Denomination Family']])->getContent();
    $denominationProperty = $this->api()->search('properties', ['term' => 'mare:denominationFamily', 'limit' => 1])->getContent();
    $denominationFamilyPropertyId = $denominationProperty{0}->id();
    echo $this->partial('common/are-filter-select', [
        'heading' => 'Denomination family',
        'filterResourceType' => 'items',
        'filterResources' => $denominationFamiles,
        'filterKey' => 'property[INDEX][joiner]=or&property[INDEX][property]=' . $denominationFamilyPropertyId . '&property[INDEX][type]=res&property[INDEX][text]'
    ]);


    $stateTerritories = $this->api()->search('items', ['resource_template_id' => $resourceTemplateIds['State/Territory']])->getContent();
    $stateTerritoriesProperty = $this->api()->search('properties', ['term' => 'mare:stateTerritory', 'limit' => 1])->getContent();
    $stateTerritoriesPropertyId = $stateTerritoriesProperty{0}->id();
    echo $this->partial('common/are-filter-select', [
        'heading' => 'State/Territory',
        'filterResourceType' => 'items',
        'filterResources' => $stateTerritories,
        'filterKey' => 'property[INDEX][joiner]=or&property[INDEX][property]=' . $stateTerritoriesPropertyId . '&property[INDEX][type]=res&property[INDEX][text]'
    ]);
  ?>
  <a href="<?php echo $this->url(null, ['action' => 'browse'], true); ?>" type="button" class="filter-submit button">Apply filters</></a>

</div>

<?php if ($itemSetShow): ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
    <h3><?php echo $translate('Item set'); ?></h3>
    <div class="metadata">
        <?php echo $itemSet->displayValues(); ?>
    </div>
    <div class="item-set-items">
    <?php echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>
<?php else: ?>
    <?php echo $this->pageTitle($translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>
<div class="browse-control-mobile">
<button type="button" class="browse-toggle closed">Tools</button>
</div>
<div class="browse-controls closed">
    <?php echo $this->pagination(); ?>
    <?php if (strpos($layoutSetting, 'toggle') !== false): ?>
    <div class="layout-toggle">
        <button type="button" aria-label="<?php echo $translate('Grid'); ?>" class="grid o-icon-grid" <?php echo $gridState; ?>></button>
        <button type="button" aria-label="<?php echo $translate('List'); ?>" class="list o-icon-list" <?php echo $listState; ?>></button>        
    </div>
    <?php endif; ?>
    <?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<ul class="resources <?php echo ($isGrid) ? 'resource-grid' : 'resource-list'; ?>">
<?php
foreach ($items as $item):
    $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]')]) : $item->displayTitle();
    $body = isset($bodyTerm) ? $item->value($bodyTerm) : $item->displayDescription();
    $attachedMedia = count($item->media());
?>  
    <li class="item resource <?php echo ($isGrid) ? '' : 'media-object'; ?>">
        <div class="resource-meta <?php echo ($isGrid) ? '' : 'media-object-section'; ?> <?php echo ($attachedMedia > 0) ? 'has-attachment' : ''; ?>">
            <h4><?php echo $item->link($heading); ?></h4>
            <?php if ($body): ?>
            <div class="description">
              <?php if ($bodyTerm == 'mare:county'): ?>
                <p>(County: <?php echo $body->asHtml(); ?>)</p>
              <?php else: ?>
                <?php echo $body; ?>
              <?php endif; ?>
            </div>
            <?php endif; ?>
        </div>
    </li>
<?php endforeach; ?>
</ul>
<?php echo ($itemSetShow) ? '</div>' : ''; ?>
<?php $this->trigger('view.browse.after'); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>