<?php
$this->headScript()->appendFile($this->assetUrl('js/browse.js'));
$translate = $this->plugin('translate');
$queryUrl = $this->url(
    'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query], true
);
?>
<div class="browse-preview-block">
<?php
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
$resourceType = $this->resourceType;
foreach ($this->resources as $resource):
    $heading = $headingTerm ? $resource->value($headingTerm, ['default' => $translate('[Untitled]')]) : $resource->displayTitle();
?>
<?php if ($resourceType == 'item'): ?>
<div class="<?php echo $resourceType; ?> resource browse-preview">
    <?php if ($thumbnail = $this->thumbnail($resource, 'large', ['alt' => 'Preview image for ' . $heading])): ?>
    <div class="resource-image">
        <?php echo $resource->linkRaw($thumbnail, null); ?>
    </div>
    <?php endif; ?>
    <div class="resource-meta">
        <h4><?php echo $resource->link($heading); ?></h4>
    </div>
</div>
<?php else: ?>
<div class="<?php echo $resourceType; ?> resource browse-preview">
    <?php if ($thumbnail = $this->thumbnail($resource, 'large', ['alt' => 'Preview image for ' . $heading])): ?>
    <?php $resourceMeta = '<span class="resource-meta">' . $heading . '</span>'; ?>
    <div class="resource-image">
        <?php echo $resource->linkRaw($thumbnail . $resourceMeta, null, ['class' => 'item-set-link']); ?>
    </div>
    <?php else: ?>
    <div class="resource-meta">
        <h4><?php echo $resource->link($heading); ?></h4>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>

<?php endforeach; ?>

<?php
if ($this->linkText && !$this->heading):
    echo $this->hyperlink($this->linkText, $queryUrl);
endif;
?>
</div>