<?php
$this->headScript()->appendFile($this->assetUrl('js/browse.js'));
$translate = $this->plugin('translate');
$queryUrl = $this->url(
    'site/resource', ['controller' => $this->resourceType, 'action' => 'browse'], ['query' => $this->query], true
);
?>

<?php
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
foreach ($this->resources as $resource):
    $heading = $headingTerm ? $resource->value($headingTerm, ['default' => $translate('[Untitled]')]) : $resource->displayTitle();
?>
<div class="<?php echo $this->resourceType; ?> resource browse-preview">
    <?php if ($thumbnail = $this->thumbnail($resource, 'large')): ?>
    <div class="resource-image">
        <?php echo $resource->linkRaw($thumbnail, null); ?>
    </div>
    <?php endif; ?>
    <div class="resource-meta">
        <h4><?php echo $resource->link($heading); ?></h4>
    </div>
</div>

<?php endforeach; ?>

<?php
if ($this->linkText && !$this->heading):
    echo $this->hyperlink($this->linkText, $queryUrl);
endif;
?>

</div>